<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-09T19:49:05 IST" name="Surefire suite" finished-at="2025-04-09T19:49:41 IST" duration-ms="36256">
    <groups>
      <group name="smoke">
        <method signature="MultipleTests.fillform_positivecase()[pri:2, instance:org.appiumDemo.Android.MultipleTests@4b5d6a01]" name="fillform_positivecase" class="org.appiumDemo.Android.MultipleTests"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2025-04-09T19:49:05 IST" name="Surefire test" finished-at="2025-04-09T19:49:41 IST" duration-ms="36256">
      <class name="org.appiumDemo.Android.MultipleTests">
        <test-method is-config="true" signature="appiumConfigure()[pri:0, instance:org.appiumDemo.Android.MultipleTests@4b5d6a01]" started-at="2025-04-09T19:49:05 IST" name="appiumConfigure" finished-at="2025-04-09T19:49:14 IST" duration-ms="9673" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appiumConfigure -->
        <test-method signature="fillform_errorValidation()[pri:1, instance:org.appiumDemo.Android.MultipleTests@4b5d6a01]" started-at="2025-04-09T19:49:14 IST" name="fillform_errorValidation" finished-at="2025-04-09T19:49:25 IST" duration-ms="11181" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at org.appiumDemo.Android.MultipleTests.fillform_errorValidation(MultipleTests.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:169)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:88)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillform_errorValidation -->
        <test-method signature="fillform_positivecase()[pri:2, instance:org.appiumDemo.Android.MultipleTests@4b5d6a01]" started-at="2025-04-09T19:49:25 IST" name="fillform_positivecase" finished-at="2025-04-09T19:49:40 IST" duration-ms="14881" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillform_positivecase -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:org.appiumDemo.Android.MultipleTests@4b5d6a01]" started-at="2025-04-09T19:49:40 IST" name="teardown" finished-at="2025-04-09T19:49:41 IST" duration-ms="468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- org.appiumDemo.Android.MultipleTests -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
